dehub:
  keycloakClient: ${KEYCLOAK_CLIENT:dehub}
  export:
    exportDirectory: ${EXPORT_DIR}
    expirationPeriodInDays: ${EXPORT_EXPIRATION_PERIOD_IN_DAYS:7}
    expiredExportsCheckRate: ${EXPIRED_EXPORTS_CHECK_RATE_IN_MILLISECONDS:3600000} // default = 1 hour

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PW}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  flyway:
    locations: "classpath:de/dataelementhub/db/migration"

springdoc:
  swagger-ui:
    url: /api-docs.json
    deep-linking: true

server:
  port: 8090
