name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  sync:

    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3
    
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/mig-frankfurt/dataelementhub.rest.git
        upstream_branch: develop
        downstream_branch: develop
        token: ${{ secrets.TOKEN }}
        SPAWN_LOGS: "false"
        
  build-and-docker:
    runs-on: ubuntu-latest
    environment: DEV
    needs: sync
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "oss-releases", "url": "https://repo.mig-frankfurt.de/repository/oss-release/" }, { "id": "oss-snapshots", "url": "https://repo.mig-frankfurt.de/repository/oss-snapshots/" }]'
        servers: '[{ "id": "oss-snapshots", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PW }}" }]'
    - name: Build with Maven
      run: mvn -U -B package --file pom.xml -Pvalidate
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ammarbr/dehub-dev-rest:latest
        no-cache: true
        
        
