name: CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:

  sync:

    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3
    
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/mig-frankfurt/dataelementhub.rest.git
        upstream_branch: develop
        downstream_branch: develop
        token: ${{ secrets.TOKEN }}
        SPAWN_LOGS: "false"
        
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: DEV
    needs: sync
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "oss-releases", "url": "https://repo.mig-frankfurt.de/repository/oss-release/" }, { "id": "oss-snapshots", "url": "https://repo.mig-frankfurt.de/repository/oss-snapshots/" }]'
        servers: '[{ "id": "oss-snapshots", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PW }}" }]'
    - name: Build with Maven
      run: mvn clean package -Dmaven.source.skip
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ammarbr/dehub-dev-rest:latest
    - name: Push the latest Docker image
      run: docker push ammarbr/dehub-dev-rest:latest
        
  redeploy:
    name: Redeploy - Webhook call
    runs-on: ubuntu-18.04
    needs: build-and-push-docker-image
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
