name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  sync:

    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v3
    
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/mig-frankfurt/dataelementhub.rest.git
        upstream_branch: develop
        downstream_branch: develop
        token: ${{ secrets.TOKEN }}
        SPAWN_LOGS: "false"
        
  docker:
    runs-on: ubuntu-latest
    environment: DEV
    needs: sync
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
          file: Dockerfile
          no-cache: true
        
        
