name: CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:    
  redeploy:
    name: Redeploy - Webhook call
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
